config/routes.rb
Rails.application.routes.draw do
  root to: 'contact_files#index'
  devise_for :users

  authenticate :user do
    resources :contact_files do
      member do
        get 'failed_contacts'
        get 'open_modal'
        post 'process_csv'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/credit_card.rb
module CreditCard
  extend ActiveSupport::Concern

  def save_credit_card
    self.franchise = detect_franchise || 'Invalid franchise'
    self.last_four_credit_card_numbers = take_last_four_credit_card_numbers
    self.credit_card = encrypt_credit_card || 'Invalid credit card'
  end

  def encrypt_credit_card
    Digest::SHA2.hexdigest(credit_card)
  rescue TypeError
    credit_card
  end

  def take_last_four_credit_card_numbers
    credit_card.try(:last, 4)
  end

  def detect_franchise
    detector = CreditCardDetector::Detector.new(credit_card)
    detector.brand_name
  end
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id                            :bigint           not null, primary key
#  email                         :string
#  name                          :string
#  phone_number                  :string
#  birth_date                    :string
#  address                       :string
#  credit_card                   :string
#  last_four_credit_card_numbers :string
#  franchise                     :string
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  contact_file_id               :bigint
#
class Contact < ApplicationRecord
  include CreditCard

  PHONE_NUMBER_REGEX = /\(([+][0-9]{1,2})\)([ .-]?)([0-9]{3})(\s|-)([0-9]{3})(\s|-)([0-9]{2})(\s|-)([0-9]{2})/.freeze
  NAME_REGEX = /[A-Za-z0-9\-\s]/.freeze

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: 'Invalid email' }, presence: true,
                    uniqueness: { scope: :contact_file_id, message: 'Email already taken' }
  validates :phone_number, format: { with: PHONE_NUMBER_REGEX, message: 'Invalid phone number' }, presence: true
  validates :name, format: { with: NAME_REGEX, message: 'Invalid Name' }, presence: true
  validates :birth_date, presence: true
  validates :address, presence: true
  validates :credit_card, presence: true

  validate :validate_birth_date
  validate :validate_credit_card

  belongs_to :contact_file

  before_save :save_credit_card

  private

  def validate_birth_date
    date = Date.parse(birth_date.to_s)
    date_format = date.strftime('%F')

    errors.add(:birth_date, 'Invalid birth date') unless date_format == birth_date
  rescue Date::Error, TypeError
    errors.add(:birth_date, 'Invalid birth date')
  end

  def validate_credit_card
    self.franchise = detect_franchise
    self.last_four_credit_card_numbers = take_last_four_credit_card_numbers
    errors.add(:credit_card, 'Invalid credit card') if franchise.nil?
  end
end

app/models/contact_file.rb
# == Schema Information
#
# Table name: contact_files
#
#  id               :bigint           not null, primary key
#  name             :string
#  original_headers :text             default([]), is an Array
#  user_id          :bigint
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  status           :integer          default("on_hold")
#
class ContactFile < ApplicationRecord
  enum status: { on_hold: 0, processing: 1, finished: 2, failed: 3 }

  has_one_attached :csv_file

  validates :name, presence: true
  validates :original_headers, presence: true
  validates :status, presence: true

  belongs_to :user
  has_many :contacts, dependent: :destroy
  has_many :failed_contacts, dependent: :destroy

  def change_status
    created_contacts = contacts.count
    created_failed_contacts = failed_contacts.count

    finished! if created_contacts.positive? || created_contacts < created_failed_contacts
    failed! if created_contacts.zero? && created_failed_contacts.positive?
  end
end

app/models/failed_contact.rb
# == Schema Information
#
# Table name: failed_contacts
#
#  id                            :bigint           not null, primary key
#  email                         :string
#  name                          :string
#  phone_number                  :string
#  birth_date                    :string
#  address                       :string
#  credit_card                   :string
#  last_four_credit_card_numbers :string
#  franchise                     :string
#  contact_file_id               :bigint
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#
class FailedContact < ApplicationRecord
  include CreditCard

  belongs_to :contact_file

  before_create :save_credit_card
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contact_files, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!

  def not_found
    raise ActionController::RoutingError, 'Not Found'
  rescue ActionController::RoutingError
    render_not_found
  end

  private

  def render_not_found
    render file: "#{Rails.root}/public/404.html", status: 404
  end
end

app/controllers/contact_files_controller.rb
class ContactFilesController < ApplicationController
  before_action :contact_file, except: %i[index new create]

  def index
    @pagy, @contact_files = pagy(current_user.contact_files.order(created_at: :desc), items: 10)
  end

  def show
    if @contact_file.on_hold?
      redirect_to contact_files_path
    else
      @pagy, @contacts = pagy(@contact_file.contacts.order(:created_at), items: 5)
    end
  end

  def new
    @contact_file = ContactFile.new
  end

  def create
    if params[:contact_file].present?
      file_path = params[:contact_file][:file].try(:path)
      filename = params[:contact_file][:file].try(:original_filename)
      result = ::ManageContactFile.new({ file_path: file_path, user: current_user, filename: filename }).call
      if result.success?
        redirect_to contact_files_path, notice: 'File loaded successfully'
      else
        redirect_to contact_files_path, alert: result.payload[:error]
      end
    else
      redirect_to contact_files_path
    end
  end

  def failed_contacts
    @pagy, @failed_contacts = pagy(@contact_file.failed_contacts.order(:created_at), items: 5)
  end

  def open_modal
    respond_to do |format|
      format.js
    end
  end

  def process_csv
    ::ProcessContactFileJob.perform_later(
      process_csv_params.to_h,
      @contact_file.id
    )

    redirect_to root_path, notice: 'CSV file is being processed. Lay on your couch and take an orange juice'
  end

  private

  def contact_file
    @contact_file = current_user.contact_files.where(id: params[:id]).take || not_found
  end

  def process_csv_params
    params.require(:process_csv).permit(:email, :name, :birth_date, :phone_number, :address, :credit_card)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/contact_files/_contacts_table.html.haml
%table.table
  %thead
    %tr
      - %w[email name birth_date phone_number address franchise last_four_credit_card_numbers created_at].each do |table_header|
        %th{:scope => "col"}
          = table_header.humanize
  %tbody
    - contacts_to_show.each do |contact|
      %tr
        %td= contact.email
        %td= contact.name
        %td= contact.birth_date
        %td= contact.phone_number
        %td= contact.address
        %td= contact.franchise
        %td= contact.last_four_credit_card_numbers
        %td= contact.created_at.to_formatted_s(:long)

.row.mb-1
  = link_to "Back", contact_files_path

.row
  = raw pagy_bootstrap_nav(@pagy)

app/views/contact_files/_form.html.haml
.container-fluid
  .row
    .modal{role:"dialog", tabindex:"-1", id: 'process_modal'}
      .modal-dialog.modal-lg{role: "document"}
        .modal-content
          = form_for :process_csv, url: process_csv_contact_file_path(@contact_file.id) do |f|
            .modal-header
              %h5.modal-title 
                = "Process #{@contact_file.name}"
              %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
                %span{"aria-hidden" => "true"} ×
            .modal-body
              %p These are your "original headers" from your csv file
              %table.table
                %thead
                  %tr
                    - @contact_file.original_headers.each do |header|
                      %th{:scope => "col"}
                        = header
              %p 
                Now you should to match your "original headers" with the system headers
              .modal-body
                %table.table
                  %thead
                    %tr
                      %th{:scope => "col"}
                        System header
                      %th{:scope => "col"}
                        Original header
                  %tbody
                    - %w[email name birth_date phone_number address credit_card].each do |contact|
                      %tr 
                        %td
                          = contact.humanize
                        %td
                          = f.select contact.to_sym, @contact_file.original_headers.sort.map{ |original_header| [original_header, original_header] }, prompt: "Select your header"
            .modal-footer
              .btn.btn-secondary{"data-dismiss" => "modal", type: "button"} Close
              = f.submit "Upload contact file", id: 'uploadButton', class: 'btn btn-primary'

app/views/contact_files/failed_contacts.html.haml
= render 'contacts_table', contacts_to_show: @failed_contacts

app/views/contact_files/index.html.haml
- if @contact_files.blank?
  .row
    %p There are not contact files yet
- else
  %table.table
    %thead
      %tr
        - %w[name status original_headers created_at actions].each do |table_header|
          %th{:scope => "col"}
            = table_header.humanize
    %tbody
      - @contact_files.each do |contact_file|
        %tr
          %td= contact_file.name
          %td= contact_file.status.humanize
          %td= contact_file.original_headers.join(', ')
          %td= contact_file.created_at.to_formatted_s(:long)
          %td
            - if contact_file.on_hold?
              = link_to "Process csv", open_modal_contact_file_path(contact_file), method: :get, class: 'btn btn-primary', remote: true
            - else 
              = link_to "View contacts", contact_file_path(contact_file), method: :get, class: 'btn btn-primary'
              = link_to "View failed contacts", failed_contacts_contact_file_path(contact_file), method: :get, class: 'btn btn-primary'

.row.mb-1
  = link_to "Upload contact files", new_contact_file_path, method: :get

.row
  = raw pagy_bootstrap_nav(@pagy)

app/views/contact_files/new.html.haml
.form-group
  = form_with model: @contact_file do |f|
    .custom-file
      = f.file_field :file, accept: ".csv"
    = f.submit "Upload contact file", id: 'uploadButton', class: 'btn btn-success'

app/views/contact_files/open_modal.js.erb
var $element = $('<%=j render partial: 'form' %>');
$('body').append($element);
$('#process_modal').modal('show')

app/views/contact_files/show.html.haml
= render 'contacts_table', contacts_to_show: @contacts

app/views/contacts/_contacts_table.html.haml
%table.table
  %thead
    %tr
      - @show_table_headers.each do |table_header|
        %th{:scope => "col"}
          = table_header.humanize
  %tbody
    - contacts_to_show.each do |contact|
      %tr
        %td= contact.email
        %td= contact.name
        %td= contact.birth_date
        %td= contact.phone_number
        %td= contact.address
        %td= contact.franchise
        %td= "****#{contact.last_four_credt_card_numbers}"
        %td= contact.created_at.strftime("%F")

.row.mb-1
  = link_to "Back", request.referer.present? ? request.referer : root_path

-# .row
  = will_paginate @contact_files, renderer: BootstrapPagination::Rails

app/views/contacts/_form.html.haml
.container-fluid
  .row
    .modal{role:"dialog", tabindex:"-1", id: 'process_modal'}
      .modal-dialog.modal-lg{role: "document"}
        .modal-content
          = form_for :process_csv, url: process_csv_contacts_path(@contact_file.id) do |f|
            .modal-header
              %h5.modal-title 
                = "Process #{@contact_file.name}"
              %button.close{"aria-label" => "Close", "data-dismiss" => "modal", type: "button"}
                %span{"aria-hidden" => "true"} ×
            .modal-body
              %p These are your "original headers" from your csv file
              %table.table
                %thead
                  %tr
                    - @contact_file.original_headers.each do |header|
                      %th{:scope => "col"}
                        = header
              %p 
                Now you should to match your "original headers" with the system headers
              .modal-body
                %table.table
                  %thead
                    %tr
                      %th{:scope => "col"}
                        System header
                      %th{:scope => "col"}
                        Original header
                  %tbody
                    - @modal_table_headers.each do |contact|
                      %tr 
                        %td
                          = contact.humanize
                        %td
                          = f.text_field contact.to_sym
            .modal-footer
              .btn.btn-secondary{"data-dismiss" => "modal", type: "button"} Close
              = f.submit "Upload contact file", id: 'uploadButton', class: 'btn btn-primary'

app/views/contacts/show_failed_contacts.html.haml
= render 'contacts_table', contacts_to_show: @failed_contacts

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Contacts
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo01", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerDemo01", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarTogglerDemo01.collapse.navbar-collapse
          %a.navbar-brand{:href => "#"} Contact importer
        - if current_user
          .my-2.my-lg-0
            = link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          .my-2.my-lg-0
            = link_to "Sign in", new_user_session_path, method: :get

      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
        
      = yield

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>